create table "users" (
	"user_id" SERIAL PRIMARY KEY,
	"username" VARCHAR 
);


create table "users2" (
    "user_id" INTEGER GENERATED by default as IDENTITY PRIMARY KEY,
    "username" VARCHAR
);

create table "users3" (
    "user_id" INTEGER GENERATED ALWAYS as IDENTITY PRIMARY KEY,
    "username" VARCHAR
);

create table "users4" (
    "user_id" INTEGER GENERATED ALWAYS as IDENTITY (start with 100 INCREMENT by 2),
    "username" VARCHAR
);